= Labs

== Lab 0: Software setup

[cols="1a,3a"]
|===
|*Download*
|*Installation notes*

|http://www.oracle.com/technetwork/pt/java/javase/downloads/jdk8-downloads-2133151.html[Java JDK 8]
|Accept the licence agreement and follow instructions.

|https://eclipse.org/downloads/[Eclipse IDE for Java Developers]
|Extract (unzip) the downloaded file, and then run.

*Windows:* In the taskbar, right click on the Eclipse icon and pin to taskbar.

*Mac OS X:* In the Dock, right click on the Eclipse icon -> Options -> Keep in Dock
|===

https://gitlab.com/lawrancej/COMP1000/blob/master/Git.adoc[Install git, run starterupper]

== Lab 1: Mad Libs!

Implement Mad Libs! Read in nouns, verbs, etc., and at the end, print out a silly story.

https://gitlab.com/lawrancej/COMP1000/blob/master/Git.adoc[How to submit work, confirm submissions, and receive updates]

== Lab 2: Unit conversion

Convert among units of temperature, mass, time, and distance:

Temperature:: Kelvin (K), Celsius (C), Fahrenheit (F)
Mass:: Kilograms (kg), Pounds (lbs), Grams (g), Ounces (oz)
Distance:: Meters (m), Kilometers (km), Miles (miles)
Time:: Seconds (s), Minutes (min), Hours (hr), Days (d), Years (y)

Example:

----
Unit converter.
Enter a measurement, unit, and new unit.
1500 g kg
1500 g = 1.5 kg
----

*Hint:* Pick a canonical unit for each unit (e.g., kelvin, grams, meters, seconds).
First convert from the starting unit to the canonical unit,
then convert from the canonical unit to the new (desired) unit.
This requires less work than converting directly between all possible pairs of units.

Feel free to:

* Add additional measures (e.g., inches, feet, centimeters)
* Keep prompting for units until the user enters quit
* Say `Invalid conversion` when asked to convert between incompatible units (e.g., inches to Fahrenheit)

https://gitlab.com/lawrancej/COMP1000/blob/master/Git.adoc[How to submit work, confirm submissions, and receive updates]

== Lab 3: Letter count / anagram checker

Flesh out the starter code in the `Submissions/src/lab3` folder.

TIP: https://gitlab.com/lawrancej/COMP1000/blob/master/Git.adoc[How to submit work, confirm submissions, and receive updates]

Complete: `min`, `max`, `sum`, `average`

`int[] letterHistogram(String text)`:: Given a string, count the number of instances of each letter (`a`-`z` only) in an array.
Use the ASCII code of each character as the index in an array.
For example, in the string `hello world`, characters `w`, `h`, `e`, `r`, `d` each occur once, `o` occurs twice, and `l` occurs 3 times.

`boolean isAnagram(String thing1, String thing2)`:: Using `letterHistogram`, determine if two Strings are http://wordsmith.org/anagram/[anagrams of each other]. Examples:
 `dormitory` is an anagram of `dirty room`; `mars` is an anagram of `rams`).

== Lab 4: Interest and Guessing game

https://a8d9f8ba-a-62cb3a1a-s-sites.googlegroups.com/site/witcomp1000fall2015/files/pa4.pdf?attachauth=ANoY7cpGQlD06LLu9ZY8V0AD7bZPjEbpE4RECmBXQdKTiDlRsT_P6WRT88Z3XropvdUmMoe9EIhAWy3JNKHCTSvDMzUuoRX1rUXdoEWK4SVhqgUsg0krMXixYMfCdvsXfEE272itnDVZqlgu-vM7yc6HFmoBaKw9njHl-dTsOGc3EH6NrpHzvU8IXlOcQB886ahgnPOGm3842MEdGcmpG-yHEu6V7bXBi4rMW3JuHRcnM0TeO3xHg94%3D&attredirects=0[Programming assignment 4]

== Lab 5: Group project setup

=== Speed dating

Goal: find a partner or partners.

Ideally, work in pairs.
Working on this individually is *very* challenging and not recommended.
Groups of 3 are okay, but larger groups are not recommended.

=== Repository setup

Goal: Set up your repository for the group project.

----
curl https://gitlab.com/lawrancej/COMP1000Project/raw/master/main.sh | bash
----

. Add each of your friend(s) as collaborators to your Gitlab repository.
. Add your friend(s) SSH urls to git.

----
cd ~/COMP1000Project
./main.sh
# Copy instructions from Local setup to command line
./gradlew eclipse
----

=== Project

Design and write a graphical program using Eclipse.
The program must be graphical and interactive (i.e., it must respond to events such as mouse clicks and key presses).
It is okay if the program is based an existing example program (indeed, studying example programs is a good way to learn, and the examples gallery is extensive).
However, if you base your program on an example, you must extend it in some nontrivial way, because passing off someone else’s work as your own is plagiarism.

Ideally, work in pairs on this program.
I do not recommend working on this project individually, as it may be overwhelming.
Groups of 3 are okay, but larger groups are not allowed (no exceptions).

Keep in mind that we have roughly two weeks remaining, so budget your time accordingly.
To begin, brainstorm program ideas with your group and browse the examples in Qt Creator.
Decide quickly on a project idea of mutual interest to your group, and commit to it (changing ideas halfway through is a recipe for disaster).
Re-implementing a well-known game, utility or application (with some reference implementation) is preferable to implementing something completely original, because the difficult design work is already done for you.
That said, I’d rather see each group will work on different projects than several groups working on similar projects.

At the end of the semester, your group must demonstrate the program to the class.
I expect everyone to explain how they contributed to their program.
If the program is based on an example, your group must show how it differs from the original example during the demonstration.
