= Lectures

== January 7: Introduce yourself

Welcome! Let's get to know each other with an icebreaker. Answer these questions:

* What is your name?
* What is your major, and why'd you pick it?
* Tell us something nobody else in the room knows about you.

== January 12: Hello, world!

How to create your first program.

. Open Eclipse
. File -> New -> Project...
. Java -> Java Project...
. Enter Project name, Finish, and Open Java Perspective
. File -> New -> Class
. Enter Main for class name, and click Finish

Copy/paste this into `Main.java`:

----
public class Main {
  public static void main(String[] args) {
    System.out.println("Hello, world!");
  }
}
----

== January 14: Java basics

Introduction to Java basics

* `main`
* Types `int`, `long`, `float`, `double`, `char`, `boolean`, `String`
* Variables, constants and naming
* Comments `// the compiler ignores this`
* Output using `System.out.println()`

== January 19: More Java basics

Let's shorten the code we developed in lab 1 using:

* `System.out.format` (namely, using `"%s"` as a placeholder and `\n` for newlines)
* Methods to allow us to define our own abstractions we can invoke and reuse.

== January 21: Packages, arrays, loops

January 21

I have an `incoming` folder under Submissions.
Look, but don't touch (for now), unless you want a merge conflict.
*Hint:* you don't want merge conflicts.

Packages allow us to organize code into groups of related things.

Arrays/Loops

== March 15

Model, View, and Controller (MVC) is a way to structure games or applications.
The model represents the state of the application and how it changes.
The view renders the model to the screen.
The controller translates keystrokes, mouse clicks, and the passage of time into model actions.

=== Model

The model represents the state of the application and how it changes over time.

Ask these questions:

. What information do I need to represent the state of my game or application?
. What are the actions or commands that can occur to update the state of the game or application?
. What other methods do I need to query the state of the game or application?

=== View

The view draws the model on the screen.

=== Controller

The controller translates keystrokes, mouse clicks, and the passage of time into model actions.

=== Example: Snake game

Model data includes all data necessary to represent game state.

[horizontal]
snake:: an array of coordinates (a pair of integers)
food:: a coordinate (a pair of integers)
direction:: up, down, left, right, or none
arena:: the rectangle (represented as a coordinate) in which the snake can move.

Model commands are any methods that update model data.
The controller (which handles user events and the passage of time) will call these actions directly or indirectly.

[horizontal]
move:: update snake based on direction and if the snake collides with something.
turn:: change direction
resize:: change arena size
grow:: the snake elongates when exposed to food
eat:: if the snake collided with food, move the food
die:: if the snake collided with itself or the arena, the snake stops.

Model queries are any useful methods that do not change state.

[horizontal]
collidesWithArena:: did the snake head bump into the wall?
collidesWithSelf:: did the snake head collide with the rest of the snake?
collidesWithFood:: did the snake head collide with the food?
